namespace Vulkan.ShaderCompiler;

public enum ShaderKind : int
{
	VertexShader = 0,
	FragmentShader,
	ComputeShader,
	GeometryShader,
	TessControlShader,
	TessEvaluationShader,
	GLSLVertexShader = VertexShader,
	GLSLFragmentShader = FragmentShader,
	GLSLComputeShader = ComputeShader,
	GLSLGeometryShader = GeometryShader,
	GLSLTessControlShader = TessControlShader,
	GLSLTessEvaluationShader = TessEvaluationShader,
	GLSLInferFromSource,
	GLSLDefaultVertexShader,
	GLSLDefaultFragmentShader,
	GLSLDefaultComputeShader,
	GLSLDefaultGeometryShader,
	GLSLDefaultTessControlShader,
	GLSLDefaultTessEvaluationShader,
	SpirvAssembly,
	RaygenShader,
	AnyhitShader,
	ClosesthitShader,
	MissShader,
	IntersectionShader,
	CallableShader,
	GLSLRaygenShader = RaygenShader,
	GLSLAnyhitShader = AnyhitShader,
	GLSLClosesthitShader = ClosesthitShader,
	GLSLMissShader = MissShader,
	GLSLIntersectionShader = IntersectionShader,
	GLSLCallableShader = CallableShader,
	GLSLDefaultRaygenShader,
	GLSLDefaultAnyhitShader,
	GLSLDefaultClosesthitShader,
	GLSLDefaultMissShader,
	GLSLDefaultIntersectionShader,
	GLSLDefaultCallableShader,
	TaskShader,
	MeshShader,
	GLSLTaskShader = TaskShader,
	GLSLMeshShader = MeshShader,
	GLSLDefaultTaskShader,
	GLSLDefaultMeshShader,
}
