namespace Vulkan;

public unsafe struct PhysicalDeviceLimits
{
	public readonly uint MaxImageDimension1D;
	public readonly uint MaxImageDimension2D;
	public readonly uint MaxImageDimension3D;
	public readonly uint MaxImageDimensionCube;
	public readonly uint MaxImageArrayLayers;
	public readonly uint MaxTexelBufferElements;
	public readonly uint MaxUniformBufferRange;
	public readonly uint MaxStorageBufferRange;
	public readonly uint MaxPushConstantsSize;
	public readonly uint MaxMemoryAllocationCount;
	public readonly uint MaxSamplerAllocationCount;
	public readonly DeviceSize BufferImageGranularity;
	public readonly DeviceSize SparseAddressSpaceSize;
	public readonly uint MaxBoundDescriptorSets;
	public readonly uint MaxPerStageDescriptorSamplers;
	public readonly uint MaxPerStageDescriptorUniformBuffers;
	public readonly uint MaxPerStageDescriptorStorageBuffers;
	public readonly uint MaxPerStageDescriptorSampledImages;
	public readonly uint MaxPerStageDescriptorStorageImages;
	public readonly uint MaxPerStageDescriptorInputAttachments;
	public readonly uint MaxPerStageResources;
	public readonly uint MaxDescriptorSetSamplers;
	public readonly uint MaxDescriptorSetUniformBuffers;
	public readonly uint MaxDescriptorSetUniformBuffersDynamic;
	public readonly uint MaxDescriptorSetStorageBuffers;
	public readonly uint MaxDescriptorSetStorageBuffersDynamic;
	public readonly uint MaxDescriptorSetSampledImages;
	public readonly uint MaxDescriptorSetStorageImages;
	public readonly uint MaxDescriptorSetInputAttachments;
	public readonly uint MaxVertexInputAttributes;
	public readonly uint MaxVertexInputBindings;
	public readonly uint MaxVertexInputAttributeOffset;
	public readonly uint MaxVertexInputBindingStride;
	public readonly uint MaxVertexOutputComponents;
	public readonly uint MaxTessellationGenerationLevel;
	public readonly uint MaxTessellationPatchSize;
	public readonly uint MaxTessellationControlPerVertexInputComponents;
	public readonly uint MaxTessellationControlPerVertexOutputComponents;
	public readonly uint MaxTessellationControlPerPatchOutputComponents;
	public readonly uint MaxTessellationControlTotalOutputComponents;
	public readonly uint MaxTessellationEvaluationInputComponents;
	public readonly uint MaxTessellationEvaluationOutputComponents;
	public readonly uint MaxGeometryShaderInvocations;
	public readonly uint MaxGeometryInputComponents;
	public readonly uint MaxGeometryOutputComponents;
	public readonly uint MaxGeometryOutputVertices;
	public readonly uint MaxGeometryTotalOutputComponents;
	public readonly uint MaxFragmentInputComponents;
	public readonly uint MaxFragmentOutputAttachments;
	public readonly uint MaxFragmentDualSrcAttachments;
	public readonly uint MaxFragmentCombinedOutputResources;
	public readonly uint MaxComputeSharedMemorySize;
	private fixed uint maxComputeWorkGroupCount[3];
	public readonly uint MaxComputeWorkGroupInvocations;
	private fixed uint maxComputeWorkGroupSize[3];
	public readonly uint SubPixelPrecisionBits;
	public readonly uint SubTexelPrecisionBits;
	public readonly uint MipmapPrecisionBits;
	public readonly uint MaxDrawIndexedIndexValue;
	public readonly uint MaxDrawIndirectCount;
	public readonly float MaxSamplerLodBias;
	public readonly float MaxSamplerAnisotropy;
	public readonly uint MaxViewports;
	private fixed uint maxViewportDimensions[2];
	private fixed float viewportBoundsRange[2];
	public readonly uint ViewportSubPixelBits;
	public readonly nuint MinMemoryMapAlignment;
	public readonly DeviceSize MinTexelBufferOffsetAlignment;
	public readonly DeviceSize MinUniformBufferOffsetAlignment;
	public readonly DeviceSize MinStorageBufferOffsetAlignment;
	public readonly int MinTexelOffset;
	public readonly uint MaxTexelOffset;
	public readonly int MinTexelGatherOffset;
	public readonly uint MaxTexelGatherOffset;
	public readonly float MinInterpolationOffset;
	public readonly float MaxInterpolationOffset;
	public readonly uint SubPixelInterpolationOffsetBits;
	public readonly uint MaxFramebufferWidth;
	public readonly uint MaxFramebufferHeight;
	public readonly uint MaxFramebufferLayers;
	public readonly SampleCount FramebufferColorSampleCounts;
	public readonly SampleCount FramebufferDepthSampleCounts;
	public readonly SampleCount FramebufferStencilSampleCounts;
	public readonly SampleCount FramebufferNoAttachmentsSampleCounts;
	public readonly uint MaxColorAttachments;
	public readonly SampleCount SampledImageColorSampleCounts;
	public readonly SampleCount SampledImageIntegerSampleCounts;
	public readonly SampleCount SampledImageDepthSampleCounts;
	public readonly SampleCount SampledImageStencilSampleCounts;
	public readonly SampleCount StorageImageSampleCounts;
	public readonly uint MaxSampleMaskWords;
	public readonly bool32 TimestampComputeAndGraphics;
	public readonly float TimestampPeriod;
	public readonly uint MaxClipDistances;
	public readonly uint MaxCullDistances;
	public readonly uint MaxCombinedClipAndCullDistances;
	public readonly uint DiscreteQueuePriorities;
	private fixed float pointSizeRange[2];
	private fixed float lineWidthRange[2];
	public readonly float PointSizeGranularity;
	public readonly float LineWidthGranularity;
	public readonly bool32 StrictLines;
	public readonly bool32 StandardSampleLocations;
	public readonly DeviceSize OptimalBufferCopyOffsetAlignment;
	public readonly DeviceSize OptimalBufferCopyRowPitchAlignment;
	public readonly DeviceSize NonCoherentAtomSize;

	public (uint x, uint y, uint z) MaxComputeWorkGroupCount => (maxComputeWorkGroupCount[0], maxComputeWorkGroupCount[1], maxComputeWorkGroupCount[2]);
	public (uint x, uint y, uint z) MaxComputeWorkGroupSize => (maxComputeWorkGroupSize[0], maxComputeWorkGroupSize[1], maxComputeWorkGroupSize[2]);
	public (uint x, uint y) MaxViewportDimensions => (maxViewportDimensions[0], maxViewportDimensions[1]);
	public (float x, float y) ViewportBoundsRange => (viewportBoundsRange[0], viewportBoundsRange[1]);
	public (float x, float y) PointSizeRange => (pointSizeRange[0], pointSizeRange[1]);
	public (float x, float y) LineWidthRange => (lineWidthRange[0], lineWidthRange[1]);
}
